SEVII_POKEMART_MapScripts::
	.byte 0
	
SixIsland_Mart_EventScript_Picnicker::
	msgbox SixIsland_Mart_Text_ShouldBuyMailAndWriteLetter, MSGBOX_NPC
	end
	
SixIsland_Mart_EventScript_BugCatcher::
	msgbox SixIsland_Mart_Text_AgathaOldestEverEliteFourMember, MSGBOX_NPC
	end
	
SevenIsland_Mart_EventScript_Lass::
	msgbox SevenIsland_Mart_Text_MonHavePersonalitiesOfTheirOwn, MSGBOX_NPC
	end

SevenIsland_Mart_EventScript_Hiker::
	msgbox SevenIsland_Mart_Text_PreparationsCompleteForRuins, MSGBOX_NPC
	end

SevenIsland_Mart_EventScript_Fisher::
	msgbox SevenIsland_Mart_Text_NeedToFishOnSevenIsland, MSGBOX_NPC
	end

SevenIsland_Mart_Text_MonHavePersonalitiesOfTheirOwn::
    .string "POKéMON have personalities of their\n"
    .string "own, just like people.\p"
    .string "My PIKACHU has a HASTY nature,\n"
    .string "so it grew to be a speedy POKéMON.$"

SevenIsland_Mart_Text_PreparationsCompleteForRuins::
    .string "Okay, preparations are complete\n"
    .string "for me to explore the RUINS.$"

SevenIsland_Mart_Text_NeedToFishOnSevenIsland::
    .string "I need to fish on SEVEN ISLAND.\p"
    .string "That will complete my fishing tour\n"
    .string "of the SEVII ISLANDS.\p"
    .string "I'd better stock up on some\n"
    .string "POKé BALLS first, though.$"

	
SixIsland_Mart_Text_AgathaOldestEverEliteFourMember::
    .string "Play with POKéMON lots and live\n"
    .string "a long life!\p"
    .string "Take AGATHA, for example.\p"
    .string "She set a record for being the\n"
    .string "oldest-ever ELITE FOUR member.\p"
    .string "She spurs me to do bigger things.$"

SixIsland_Mart_Text_ShouldBuyMailAndWriteLetter::
    .string "I should buy some MAIL and write\n"
    .string "him a letter…$"
